version: '3.8'


services:

  my_app_rust:

    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - '8080'

    deploy:
      replicas: 4

    restart: always

    environment:
      - PING_LISTEN_PORT=8080

    networks:
      - front-network

  proxy:

    image: nginx:latest
    command: sh -c "rm -rf /docker-entrypoint.d/* && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    depends_on:
      - my_app_rust
    networks:
      - front-network

networks:
  front-network:
    driver: bridge

volumes:
  db_data:

